--세번째 자리에서 반올림하려면 ROUND(X,2)여야 함 또한 조건을 잘 살필 것("서울")
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO I, REST_REVIEW R
WHERE I.REST_ID = R.REST_ID AND I.ADDRESS LIKE "서울%"
GROUP BY I.REST_ID
ORDER BY 6 DESC, 4 DESC;
