SELECT PT_NAME, PT_NO, GEND_CD, AGE, IF(TLNO IS NOT NULL, TLNO, 'NONE')
FROM PATIENT
WHERE GEND_CD = "W" AND AGE <= 12
ORDER BY AGE DESC, PT_NAME ASC;

--IF(TLNO IS NOT NULL, TLNO, 'NONE')
--조건식의 결과가 TRUE면 두번째 인자를 리턴하고, FALSE라면 세번째 인자를 리턴한다.
